apiVersion: extensions/v1beta1
kind: Ingress    #this will configure rules on Ingress Controller. We first need to create Ingress Controller. that will be another yaml file
metadata:
  name: kubia
spec:
  rules:
  - host: kubia.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubia-nodeport  # we dont need to use nodeport. we can use cluster IP service
          servicePort: 80
