apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
         - kubia
      - key: app1
        operator: In
        values:
         - kubia1
  template:
    metadata:
      labels:
        app: kubia
        app1: kubia1
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
